services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app:cached
    command: sh -c 'trap "exit 0" TERM; tail -f /dev/null & wait'

  pgmq:
    image: ghcr.io/pgmq/pg18-pgmq:v1.11.1
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5432:5432"
