on:
  workflow_dispatch: ~
  push:
    branches: ['main', '*.*.x']
  pull_request: ~

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.3", "8.4"]
        dependencies: ["locked", "lowest", "highest"]
    steps:
      - uses: actions/checkout@v4
      - name: Start pgmq
        run: |
          docker run -d \
            --name pgmq-postgres \
            -p 5432:5432 \
            -e POSTGRES_PASSWORD=postgres \
            ghcr.io/pgmq/pg18-pgmq:v1.8.0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-file: development
          tools: composer:v2
          extensions: pcntl
          ini-values: disable_functions=pcntl_fork
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
          dependency-versions: ${{ matrix.dependencies }}
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH || '{}' }}
      - run: THESIS_PGMQ_DSN="host=localhost user=postgres password=postgres" composer test
